spring:
  profiles: dev

  # Config PostgresSql
  datasource:
    url: jdbc:postgresql://localhost:4040/booklibrary
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop

    # Format_SQL
    properties:
      hibernate:
        show_sql: true
        format_sql: true