spring:
  profiles:
    active: "dev"

  application:
    name: book-library-service

  # Font log
  output:
    ansi:
      enabled: ALWAYS

  # Multipart max size
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

# Port
server:
  port: 8010


# Logging
logging:
  level:
    root: WARN
    org:
      springframework:
        web: INFO
      hibernate: ERROR
    com:
      study:
        BookLibrary: DEBUG