spring:
  profiles: prod

  # Config PostgresSql
  datasource:
    url: jdbc:postgresql://localhost:5432/booklibrary
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update